#### Numpy methods:-
1. np.sort()
2. np.append()
3. np.concatenate()
4. np.stack()
5. np.cumsum()
6. np.cumprod()
7. np.argmax()
8. np.argmin()
9. np.percentile()
10. np.where()
11. np.put()
12. np.flip()
13. np.clip()
14. np.unique()
15. np.expand_dims()
16. np.isin()
17. np.histogram()
18. np.corrcoef()
19. np.delete()
20. set functions :
    
        np.union1d()
    
        np.setdiff1d()

        np.setxor1d()

        np.intersect1d()
    
        np.isin()

In [1]:
import numpy as np

#### sort()

In [2]:
arr1 = np.array([1,3,6,4,8,3,9])
np.sort(arr1) #ascending

array([1, 3, 3, 4, 6, 8, 9])

In [3]:
np.sort(arr1)[::-1] #ascending but changhed to desc by slicing

array([9, 8, 6, 4, 3, 3, 1])

In [4]:
arr2 = np.random.randint(10,50,12).reshape(4,3)
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [5]:
np.sort(arr2) # by default row wise

array([[25, 30, 30],
       [19, 21, 23],
       [22, 26, 38],
       [16, 23, 27]], dtype=int32)

In [6]:
np.sort(arr2, axis = 1)[::-1] # row wise desc order
                                # after sorting the last row became first, 2nd last 2nd and so on

array([[16, 23, 27],
       [22, 26, 38],
       [19, 21, 23],
       [25, 30, 30]], dtype=int32)

In [7]:
np.sort(arr2, axis = 0) # col wise asc order

array([[23, 16, 19],
       [23, 21, 22],
       [26, 30, 25],
       [30, 38, 27]], dtype=int32)

In [8]:
np.sort(arr2, axis = 0)[::-1] # col wise desc order

array([[30, 38, 27],
       [26, 30, 25],
       [23, 21, 22],
       [23, 16, 19]], dtype=int32)

#### concatenate() : extends the dimensions

In [9]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [10]:
arr3 = np.array([2,4,2,6,7,8,5])
arr3

array([2, 4, 2, 6, 7, 8, 5])

In [11]:
np.concatenate((arr1,arr3)) # 

array([1, 3, 6, 4, 8, 3, 9, 2, 4, 2, 6, 7, 8, 5])

In [12]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [13]:
arr4 = np.arange(10,22).reshape(4,3)
arr4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [14]:
np.concatenate((arr2,arr4)) # row wise /  vertical conatenation by default

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [15]:
arr5 = np.random.randint(20,50,18).reshape(6,3)
arr5

array([[33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]], dtype=int32)

In [16]:
np.concatenate((arr4,arr5))  # shape of arrays : (4,3) , (6,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]])

In [17]:
np.concatenate((arr2,arr4,arr5)) # shape of arrays : (4,3) , (4,3) , (6,3)

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]])

In [18]:
np.concatenate((arr2,arr5),axis = 0) # row wise /  vertical conatenation when axis = 0

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27],
       [33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]], dtype=int32)

In [19]:
np.concatenate((arr2,arr4),axis = 1) # col wise /  horizontal conatenation when axis = 1

array([[30, 30, 25, 10, 11, 12],
       [23, 21, 19, 13, 14, 15],
       [26, 38, 22, 16, 17, 18],
       [23, 16, 27, 19, 20, 21]])

In [20]:
arr6 = np.arange(50,58).reshape(4,2)
arr6

array([[50, 51],
       [52, 53],
       [54, 55],
       [56, 57]])

In [21]:
np.concatenate((arr2,arr6), axis = 1)  # shape of arrays : (4,3) , (4,2) 

array([[30, 30, 25, 50, 51],
       [23, 21, 19, 52, 53],
       [26, 38, 22, 54, 55],
       [23, 16, 27, 56, 57]])

In [22]:
arr7 =  np.arange(50,70).reshape(4,5)
arr7

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [23]:
np.concatenate((arr2,arr6,arr7), axis = 1)  # shape of arrays : (4,3) , (4,2) , (4,7)

array([[30, 30, 25, 50, 51, 50, 51, 52, 53, 54],
       [23, 21, 19, 52, 53, 55, 56, 57, 58, 59],
       [26, 38, 22, 54, 55, 60, 61, 62, 63, 64],
       [23, 16, 27, 56, 57, 65, 66, 67, 68, 69]])

#### stack() : similar to concatenate, only difference is it increases dimensions and concatenation doesn't 

In [24]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [25]:
arr3

array([2, 4, 2, 6, 7, 8, 5])

In [26]:
np.stack((arr1,arr3)) # 1d -> 2d  # axis = 0, rows increase

array([[1, 3, 6, 4, 8, 3, 9],
       [2, 4, 2, 6, 7, 8, 5]])

In [27]:
np.stack((arr1,arr3), axis = 1)  # 1d -> 2d  # axis = 1, cols increase

array([[1, 2],
       [3, 4],
       [6, 2],
       [4, 6],
       [8, 7],
       [3, 8],
       [9, 5]])

In [28]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [29]:
arr4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [30]:
np.stack((arr2,arr4),axis = 0)  #2d->3d

array([[[30, 30, 25],
        [23, 21, 19],
        [26, 38, 22],
        [23, 16, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]]])

In [31]:
np.stack((arr2,arr4),axis = 1)  

array([[[30, 30, 25],
        [10, 11, 12]],

       [[23, 21, 19],
        [13, 14, 15]],

       [[26, 38, 22],
        [16, 17, 18]],

       [[23, 16, 27],
        [19, 20, 21]]])

#### append()

In [32]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [33]:
arr3

array([2, 4, 2, 6, 7, 8, 5])

In [34]:
 # 1d arrays:

np.append(arr1,arr3)

array([1, 3, 6, 4, 8, 3, 9, 2, 4, 2, 6, 7, 8, 5])

In [35]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [36]:
arr5

array([[33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]], dtype=int32)

In [37]:
np.append(arr2,arr5)

array([30, 30, 25, 23, 21, 19, 26, 38, 22, 23, 16, 27, 33, 20, 30, 25, 43,
       49, 25, 44, 24, 23, 42, 38, 41, 27, 32, 29, 29, 27], dtype=int32)

In [38]:
arr4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [39]:
np.append(arr2,arr4, axis = 1)  # no. of rows must be same if axis = 1, cols may differ in no.

array([[30, 30, 25, 10, 11, 12],
       [23, 21, 19, 13, 14, 15],
       [26, 38, 22, 16, 17, 18],
       [23, 16, 27, 19, 20, 21]])

In [40]:
arr6

array([[50, 51],
       [52, 53],
       [54, 55],
       [56, 57]])

In [41]:
np.append(arr2,arr5, axis = 0)  # no. of cols must be same if axis = 0, rows may differ in no.

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27],
       [33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]], dtype=int32)

#### cumsum() & cumprod()

In [42]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [43]:
np.cumsum(arr1)

array([ 1,  4, 10, 14, 22, 25, 34])

In [44]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [45]:
np.cumsum(arr2) # 2d -> 1d if axis not mentioned

array([ 30,  60,  85, 108, 129, 148, 174, 212, 234, 257, 273, 300])

In [46]:
np.cumsum(arr2, axis= 0) # col wise

array([[ 30,  30,  25],
       [ 53,  51,  44],
       [ 79,  89,  66],
       [102, 105,  93]])

In [47]:
np.cumsum(arr2, axis= 1) # row wise

array([[30, 60, 85],
       [23, 44, 63],
       [26, 64, 86],
       [23, 39, 66]])

In [48]:
np.cumprod(arr1)

array([    1,     3,    18,    72,   576,  1728, 15552])

In [49]:
np.cumprod(arr2, axis = 1)

array([[   30,   900, 22500],
       [   23,   483,  9177],
       [   26,   988, 21736],
       [   23,   368,  9936]])

In [50]:
np.cumprod(arr2, axis = 0)

array([[    30,     30,     25],
       [   690,    630,    475],
       [ 17940,  23940,  10450],
       [412620, 383040, 282150]])

#### percentile()

In [51]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [52]:
np.percentile(arr1,20) # 20 percentile of arr1

np.float64(3.0)

In [53]:
np.percentile(arr1,50)

np.float64(4.0)

In [54]:
np.percentile(arr1,100) # max num

np.float64(9.0)

In [55]:
np.percentile(arr1,0) # min num

np.float64(1.0)

In [56]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [57]:
np.percentile (arr2,100, axis = 1) # row wise 100 percentile

array([30., 23., 38., 27.])

In [58]:
np.percentile (arr2,53 , axis = 0) # row wise 100 percentile

array([24.77, 26.31, 23.77])

#### argmax() & argmin()

In [59]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [60]:
np.argmax(arr1) # returns index of max element

np.int64(6)

In [61]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [62]:
np.argmax(arr2) # flattens the array into 1d array and then returns the index of max element

np.int64(7)

In [63]:
np.argmax(arr2, axis = 0)

array([0, 2, 3])

In [64]:
np.argmin(arr2, axis = 0)

array([1, 3, 1])

##### unique()

In [65]:
np.unique(arr2)

array([16, 19, 21, 22, 23, 25, 26, 27, 30, 38], dtype=int32)

##### expand_dims()

In [66]:
arr1.shape

(7,)

In [67]:
np.expand_dims(arr1, axis = 0)

array([[1, 3, 6, 4, 8, 3, 9]])

In [68]:
np.expand_dims(arr1, axis = 0).shape

(1, 7)

In [69]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [3],
       [6],
       [4],
       [8],
       [3],
       [9]])

In [70]:
np.expand_dims(arr1, axis = 1).shape

(7, 1)

#### where()

In [71]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [72]:
np.where(arr1>6) # indexes of elements >6

(array([4, 6]),)

In [73]:
arr1[np.where(arr1>6)] # elements >6

array([8, 9])

In [74]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [75]:
np.where(arr2<30)  # returns tuple of two arrays one having index rowise and another col wise

(array([0, 1, 1, 1, 2, 2, 3, 3, 3]), array([2, 0, 1, 2, 0, 2, 0, 1, 2]))

In [76]:
# replace elements greater than 30 with 0
np.where(arr2>30, 0, arr2)

array([[30, 30, 25],
       [23, 21, 19],
       [26,  0, 22],
       [23, 16, 27]], dtype=int32)

In [77]:
# replace elements greater than 30 with true
np.where(arr2>30, "true", arr2)

array([['30', '30', '25'],
       ['23', '21', '19'],
       ['26', 'true', '22'],
       ['23', '16', '27']], dtype='<U11')

#### histogram()

In [78]:
np.histogram(arr1, bins=[0,4,8]) # 3 ele in 0-4, 3 in 4-8 range 

(array([3, 3]), array([0, 4, 8]))

In [79]:
np.histogram(np.random.randint(10,50,60), bins= [0,10,20,30,40,50])

(array([ 0, 19, 12, 12, 17]), array([ 0, 10, 20, 30, 40, 50]))

#### corrcoef()

In [80]:
salary = np.array([2000,4000,3000,6000])
experience = np.array([1,5,6,5])
np.corrcoef(salary, experience) # positive relation means increase in exp results increase in salary 

array([[1.        , 0.55014856],
       [0.55014856, 1.        ]])

In [81]:
salary = np.array([2000,4000,3000,6000])
experience = np.array([6,5,2,1])
np.corrcoef(salary, experience) # negative relation means increase in exp results decrease in salary 

array([[ 1.        , -0.69693205],
       [-0.69693205,  1.        ]])

In [82]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([7, 2, 9, 4, 10])  # Random pattern, no trend
print(np.corrcoef(x, y))


[[1.         0.37628835]
 [0.37628835 1.        ]]


In [116]:
arr4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [117]:
arr5

array([[33, 20, 30],
       [25, 43, 49],
       [25, 44, 24],
       [23, 42, 38],
       [41, 27, 32],
       [29, 29, 27]], dtype=int32)

In [118]:
np.corrcoef(arr4,arr5)

array([[ 1.        ,  1.        ,  1.        ,  1.        , -0.22036595,
         0.96076892, -0.04436783,  0.74875312, -0.63428533, -0.8660254 ],
       [ 1.        ,  1.        ,  1.        ,  1.        , -0.22036595,
         0.96076892, -0.04436783,  0.74875312, -0.63428533, -0.8660254 ],
       [ 1.        ,  1.        ,  1.        ,  1.        , -0.22036595,
         0.96076892, -0.04436783,  0.74875312, -0.63428533, -0.8660254 ],
       [ 1.        ,  1.        ,  1.        ,  1.        , -0.22036595,
         0.96076892, -0.04436783,  0.74875312, -0.63428533, -0.8660254 ],
       [-0.22036595, -0.22036595, -0.22036595, -0.22036595,  1.        ,
        -0.48225283, -0.96467958, -0.81155403,  0.89386904, -0.29686613],
       [ 0.96076892,  0.96076892,  0.96076892,  0.96076892, -0.48225283,
         1.        ,  0.23444975,  0.90321995, -0.82382073, -0.69337525],
       [-0.04436783, -0.04436783, -0.04436783, -0.04436783, -0.96467958,
         0.23444975,  1.        ,  0.6289757 

#### isin()

In [83]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [115]:
np.isin(arr2,43)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [85]:
np.isin(arr2,[43,12] )

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [86]:
np.isin(arr2,[43,12,44,99,67] )

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

#### flip()

In [87]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [88]:
np.flip(arr1)

array([9, 3, 8, 4, 6, 3, 1])

In [89]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [90]:
np.flip(arr2) # flips cols val then rows val

array([[27, 16, 23],
       [22, 38, 26],
       [19, 21, 23],
       [25, 30, 30]], dtype=int32)

In [91]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [92]:
np.flip(arr2, axis=0) # flips cols i.e, last val in each col comes at top

array([[23, 16, 27],
       [26, 38, 22],
       [23, 21, 19],
       [30, 30, 25]], dtype=int32)

In [93]:
np.flip(arr2, axis=1) # flips cols i.e, last val in each row comes at top

array([[25, 30, 30],
       [19, 21, 23],
       [22, 38, 26],
       [27, 16, 23]], dtype=int32)

#### put() : permanent operation

In [94]:
arr1

array([1, 3, 6, 4, 8, 3, 9])

In [95]:
np.put(arr1, [0],200 )

In [96]:
arr1[np.put(arr1, 0,200 )]

array([[200,   3,   6,   4,   8,   3,   9]])

In [97]:
print(np.put(arr1, 0,200 ))

None


In [98]:
arr2

array([[30, 30, 25],
       [23, 21, 19],
       [26, 38, 22],
       [23, 16, 27]], dtype=int32)

In [99]:
arr2[np.put(arr2, [0,4],[200,300] )] ## flattens the array and then replaces values

array([[[200,  30,  25],
        [ 23, 300,  19],
        [ 26,  38,  22],
        [ 23,  16,  27]]], dtype=int32)

In [113]:
arr2 ## original array changed 

array([[200,  30,  25],
       [ 23, 300,  19],
       [ 26,  38,  22],
       [ 23,  16,  27]], dtype=int32)

In [100]:
np.delete(arr2,2) # 2nd index item i.e.,14 is deleted || temporary opr || result is flattened array 

array([200,  30,  23, 300,  19,  26,  38,  22,  23,  16,  27], dtype=int32)

In [101]:
arr2

array([[200,  30,  25],
       [ 23, 300,  19],
       [ 26,  38,  22],
       [ 23,  16,  27]], dtype=int32)

#### clip()

In [102]:
np.clip(arr2, a_max= 35, a_min= 15)

array([[35, 30, 25],
       [23, 35, 19],
       [26, 35, 22],
       [23, 16, 27]], dtype=int32)

#### set methods:-

In [103]:
arr1

array([200,   3,   6,   4,   8,   3,   9])

In [104]:
arr2

array([[200,  30,  25],
       [ 23, 300,  19],
       [ 26,  38,  22],
       [ 23,  16,  27]], dtype=int32)

In [105]:
arr3

array([2, 4, 2, 6, 7, 8, 5])

In [106]:
np.union1d(arr1,arr2) # elements in arr1 arr2

array([  3,   4,   6,   8,   9,  16,  19,  22,  23,  25,  26,  27,  30,
        38, 200, 300])

In [107]:
np.intersect1d(arr1,arr2) # elements both in arr1 arr2

array([200])

In [108]:
np.setdiff1d(arr1,arr3) # elements only in arr1

array([  3,   9, 200])

In [109]:
np.setdiff1d(arr1,arr2) # elements only in arr1

array([3, 4, 6, 8, 9])

In [110]:
np.setdiff1d(arr2,arr1) # elements only in arr2

array([ 16,  19,  22,  23,  25,  26,  27,  30,  38, 300], dtype=int32)

In [111]:
np.setxor1d(arr1,arr2) # elements of both arr1 arr2 that are uncommon

array([  3,   4,   6,   8,   9,  16,  19,  22,  23,  25,  26,  27,  30,
        38, 300])

In [112]:
np.in1d(arr1, 200)

C:\Users\Hp\AppData\Local\Temp\ipykernel_17200\2434702953.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1, 200)


array([ True, False, False, False, False, False, False])