#### Accessing elements of an array:-
1. normal indexing
2. slicing
3. fancy indexing
4. boolean indexing

In [2]:
import numpy as np

In [6]:
arr = np.arange(10,30).reshape(5,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [8]:
# 2nd row
arr[1]

array([14, 15, 16, 17])

In [13]:
# last row
arr[-1]

array([26, 27, 28, 29])

In [12]:
arr[-1, :]

array([26, 27, 28, 29])

In [10]:
# 3rd col
arr[:,2]

array([12, 16, 20, 24, 28])

In [14]:
# 10 11 14 15
arr[0:2,0:2]

array([[10, 11],
       [14, 15]])

In [15]:
# 10 13 26,29
arr[::4,::3]

array([[10, 13],
       [26, 29]])

In [16]:
# 10 13 18 21 26 29
arr[::2,::3]

array([[10, 13],
       [18, 21],
       [26, 29]])

In [18]:
# 18 20
arr[2,::2]

array([18, 20])

In [22]:
# 24 25
arr[-2,-2::]

array([24, 25])

In [24]:
# 19 20 23 24
arr[2:-1, 1:3]

array([[19, 20],
       [23, 24]])

In [25]:
## fancy indexing

arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [28]:
# 14,12,24,27
arr[[1,0,3,4], [0,2,2,1]]

array([14, 12, 24, 27])

In [29]:
# 1,4,5 th row
arr[[0,3,4]]

array([[10, 11, 12, 13],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [32]:
# 1 2 4th col
arr[:,[0,1,-1]]

array([[10, 11, 13],
       [14, 15, 17],
       [18, 19, 21],
       [22, 23, 25],
       [26, 27, 29]])

In [33]:
# boolean indexing
# elements greater than 15
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [34]:
arr>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
arr[arr>5] # masking

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [36]:
arr[~(arr%2==0)] # odd numbers

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [37]:
arr[(arr%4==0)]

array([12, 16, 20, 24, 28])