#### NumPy Array Methods:-
1. round()
2. min()/max()
3. mean()/median()/mode()
3.var()/std()
4. log()/exp()
5. dot()/transpose()


In [2]:
import numpy as np

In [5]:
arr = (np.random.random(10).reshape(5,2))*100
arr.round()

array([[54., 75.],
       [28.,  9.],
       [11., 17.],
       [74., 73.],
       [68., 42.]])

In [9]:
arr = arr.round(2).astype(int)
arr

array([[53, 74],
       [28,  9],
       [11, 17],
       [74, 72],
       [67, 42]])

In [10]:
arr.max()

np.int64(74)

In [28]:
np.max(arr)

np.int64(74)

In [11]:
int(arr.max())

74

In [12]:
arr.max().item()

74

In [19]:
arr

array([[53, 74],
       [28,  9],
       [11, 17],
       [74, 72],
       [67, 42]])

In [22]:
arr.max(axis = 1) #row wise max element

array([74, 28, 17, 74, 67])

In [30]:
np.max(arr, axis = 0)

array([74, 74])

In [14]:
arr.min().item()

9

In [23]:
arr.min(axis=0) ## column wise min element

array([11,  9])

In [24]:
arr.std().item()

25.47959968288356

In [17]:
arr.mean().item()

44.7

In [25]:
arr.var(axis=1)

array([110.25,  90.25,   9.  ,   1.  , 156.25])

In [27]:
np.log(arr)

array([[3.97029191, 4.30406509],
       [3.33220451, 2.19722458],
       [2.39789527, 2.83321334],
       [4.30406509, 4.27666612],
       [4.20469262, 3.73766962]])

#### looping on arrays:-

In [36]:
arr1 = np.linspace(2,6,5)
arr1

array([2., 3., 4., 5., 6.])

In [37]:
for i in arr1:
    print(i)

2.0
3.0
4.0
5.0
6.0


In [32]:
arr

array([[53, 74],
       [28,  9],
       [11, 17],
       [74, 72],
       [67, 42]])

In [31]:
for i in arr:
    print(i)

[53 74]
[28  9]
[11 17]
[74 72]
[67 42]


In [40]:
## nditer()

for i in np.nditer(arr):
    print(i)

53
74
28
9
11
17
74
72
67
42


#### changing array shape:-
1. reshape()
2. ravel()
3. transpose

In [42]:
arr.shape

(5, 2)

In [43]:
arr.reshape(2,5)

array([[53, 74, 28,  9, 11],
       [17, 74, 72, 67, 42]])

In [44]:
arr.ravel() ## changed 2d to 1d

array([53, 74, 28,  9, 11, 17, 74, 72, 67, 42])

In [47]:
arr

array([[53, 74],
       [28,  9],
       [11, 17],
       [74, 72],
       [67, 42]])

In [49]:
arr = arr.transpose() # row became col and col became row
arr

array([[53, 28, 11, 74, 67],
       [74,  9, 17, 72, 42]])

In [50]:
arr.T

array([[53, 74],
       [28,  9],
       [11, 17],
       [74, 72],
       [67, 42]])

#### splitting:-
1. hsplit()
2. vsplit()

In [52]:
arr

array([[53, 28, 11, 74, 67],
       [74,  9, 17, 72, 42]])

In [59]:
np.hsplit(arr, 5) # returns a list of 5 2darrays

[array([[53],
        [74]]),
 array([[28],
        [ 9]]),
 array([[11],
        [17]]),
 array([[74],
        [72]]),
 array([[67],
        [42]])]

In [58]:
np.hsplit(arr,1)

[array([[53, 28, 11, 74, 67],
        [74,  9, 17, 72, 42]])]

In [61]:
np.vsplit(arr,1)

[array([[53, 28, 11, 74, 67],
        [74,  9, 17, 72, 42]])]

In [62]:
np.vsplit(arr,2)

[array([[53, 28, 11, 74, 67]]), array([[74,  9, 17, 72, 42]])]

#### stacking:-
1. hstack()
2. vstack()

In [65]:
arr1 = arr
arr1

array([[53, 28, 11, 74, 67],
       [74,  9, 17, 72, 42]])

In [67]:
arr2 = np.arange(10,20).reshape(2,5)
arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
np.hstack((arr1,arr2))

array([[53, 28, 11, 74, 67, 10, 11, 12, 13, 14],
       [74,  9, 17, 72, 42, 15, 16, 17, 18, 19]])

In [70]:
np.vstack((arr1,arr2))

array([[53, 28, 11, 74, 67],
       [74,  9, 17, 72, 42],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
arr3 = np.arange(20,30).reshape(2,5)
arr3

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [73]:
np.hstack((arr1,arr2,arr3))

array([[53, 28, 11, 74, 67, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
       [74,  9, 17, 72, 42, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [74]:
np.vstack((arr1,arr2,arr3))

array([[53, 28, 11, 74, 67],
       [74,  9, 17, 72, 42],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])