In [1]:
import numpy as np

#### Q-1 Create a null vector of size 10 but the fifth value which is 1.


In [4]:
null_vector = np.zeros(10, dtype = int)
null_vector[4]=1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### Q-2 Ask user to input two numbers m,n. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.


In [18]:
m = int(input("enter the number of rows: "))
n = int(input("enter the number of cols: "))
arr = np.random.randint(10,20,m*n).reshape(m,n)
print(arr)
print()
print("mean is:", np.mean(arr))


enter the number of rows:  3
enter the number of cols:  4


[[13 11 19 11]
 [19 12 14 19]
 [18 17 16 10]]

mean is: 14.916666666666666


#### Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.


In [21]:
def arr2d(a,b):
    arr = np.zeros((a,b))
    arr[0,:]=1
    arr[-1,:]=1
    arr[:,0]=1
    arr[:,-1]=1
    return arr
arr2d(6,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [22]:
arr = np.random.random(10)
arr

array([0.24226459, 0.27256071, 0.40481087, 0.7798563 , 0.22514777,
       0.35214498, 0.58195149, 0.70688401, 0.55202495, 0.19391117])

#### Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it

No.  we can not create an identity matrix of 3,4 as identity matrix is a square matrix with digonal elements equal to 1

#### Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [24]:

arr = np.round(np.linspace(0,4,25), 2).reshape(5,5)
arr

array([[0.  , 0.17, 0.33, 0.5 , 0.67],
       [0.83, 1.  , 1.17, 1.33, 1.5 ],
       [1.67, 1.83, 2.  , 2.17, 2.33],
       [2.5 , 2.67, 2.83, 3.  , 3.17],
       [3.33, 3.5 , 3.67, 3.83, 4.  ]])

#### Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.
point = np.array([2,3]) 


In [3]:
## Method 1:-

p_arr = np.random.randint(1,101,20).reshape(10,2)
p_arr

array([[81, 56],
       [98, 54],
       [50, 99],
       [61, 63],
       [42, 36],
       [26, 47],
       [63, 94],
       [ 9, 38],
       [55, 32],
       [43, 23]], dtype=int32)

In [4]:
point = np.array([2,3]) 
point

array([2, 3])

In [11]:
def dist(arr1, arr2):
    distance_arr = [ ]
    for i in arr1:
        distance = np.round(np.array((((i[0]-arr2[0])**2 ) + ((i[1]-arr2[1])**2 ))**0.5), 2)
        distance_arr = np.append(distance_arr, distance)
    return distance_arr
dist(p_arr, point)

array([ 95.13, 108.71, 107.33,  84.15,  51.86,  50.12, 109.55,  35.69,
        60.42,  45.62])

In [14]:
## Method 2:-

def dist_point(arr1, arr2):
    return np.round(np.sqrt(np.sum(((arr1-arr2)**2), axis = 1)),2) # numpy broadcast arr2 from (1,2) to (10,2)
dist_point(p_arr, point)

array([ 95.13, 108.71, 107.33,  84.15,  51.86,  50.12, 109.55,  35.69,
        60.42,  45.62])

arr1 has shape (10,2) → 10 points [x,y].

arr2 is one point [x0,y0].

NumPy broadcasts [x0,y0] to every row of arr1.

Result: array of shape (10,2) containing differences [x-x0, y-y0].

(arr1 - arr2)**2

Squares each difference.

np.sum(..., axis=1)

Sums along each row 

#### Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(99,shape)

NameError: name 'shape' is not defined