In [1]:
import numpy as np

In [4]:
# Q-1 Create a null vector of size 10 but the fifth value which is 1.

null_vector = np.zeros(10, dtype = int)
null_vector[4]=1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
# Q-2 Ask user to input two numbers m,n. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

m = int(input("enter the number of rows: "))
n = int(input("enter the number of cols: "))
arr = np.random.randint(10,20,m*n).reshape(m,n)
print(arr)
print()
print("mean is:", np.mean(arr))


enter the number of rows:  3
enter the number of cols:  4


[[16 11 11 15]
 [16 13 18 15]
 [11 14 10 18]]

mean is: 14.0


In [21]:
# Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

def arr2d(a,b):
    arr = np.zeros((a,b))
    arr[0,:]=1
    arr[-1,:]=1
    arr[:,0]=1
    arr[:,-1]=1
    return arr
arr2d(6,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

arr = np.random.random(10)
arr

array([0.24226459, 0.27256071, 0.40481087, 0.7798563 , 0.22514777,
       0.35214498, 0.58195149, 0.70688401, 0.55202495, 0.19391117])

In [24]:
# Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.
arr = np.round(np.linspace(0,4,25), 2).reshape(5,5)
arr

array([[0.  , 0.17, 0.33, 0.5 , 0.67],
       [0.83, 1.  , 1.17, 1.33, 1.5 ],
       [1.67, 1.83, 2.  , 2.17, 2.33],
       [2.5 , 2.67, 2.83, 3.  , 3.17],
       [3.33, 3.5 , 3.67, 3.83, 4.  ]])

In [ ]:
# Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.
# point = np.array([2,3]) 

