In [1]:
import numpy as np

#### Different ways to create an array:-
1. array()
2. arange()
3. random.random()
4. linspace()
5. ones()
6. zeros()
7. identity()


In [3]:
# 1. array()

#1d array
arr1  = np.array(['1','2','3'])
arr1

array(['1', '2', '3'], dtype='<U1')

In [4]:
#2d array
arr2= np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#3d array
arr3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
# 2. arange():-

#1d array
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
#2d array
arr2 = np.arange(1,11).reshape(2,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#3d array
arr3= np.arange(1,19).reshape(2,3,3)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
#4d array
arr4 = np.arange(1,17).reshape(2,2,2,2)
arr4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [14]:
# 3. random():-

#1d array

arr1 = np.random.random(5)
arr1

array([0.46183976, 0.14513251, 0.5728098 , 0.7704184 , 0.53888219])

In [15]:
#2d array

arr2 = np.random.random(6).reshape(3,2)
arr2

array([[0.95967534, 0.05297973],
       [0.06896966, 0.73724413],
       [0.37628905, 0.2099    ]])

In [18]:
#3d array

arr3 = (np.random.random(12).reshape(2,3,2))*100
arr3

array([[[73.65740889, 83.77764329],
        [77.63182908, 75.67810591],
        [58.29586437, 97.82559309]],

       [[40.67706462, 40.64672532],
        [78.5910881 , 43.52778256],
        [39.62602804, 63.12742679]]])

In [20]:
#4. ones()

# 1d array
arr1= np.ones((2,))
arr1

array([1., 1.])

In [22]:
# 2d array
arr2= np.ones((2,6))
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
# 3d array
arr3 = np.ones((2,4,3))
arr3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [3]:
#5. zeros() :-

#1d array
arr1 = np.zeros(5)
#arr1 = np.zeros((5,))
arr1

array([0., 0., 0., 0., 0.])

In [4]:
arr1 = np.zeros((5,))
arr1

array([0., 0., 0., 0., 0.])

In [29]:
#2d array
arr2 = np.zeros((5,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#3d array
arr3 = np.zeros((3,5,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
#6. identity():-

# 2d array
arr2 = np.identity(12)
arr2

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
# 3d array
arr2 = np.identity(12).reshape(6,2,12)
arr2

array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]])

In [43]:
# 7. linspace():-

#1d array
arr1 = np.linspace(2,10,5)
arr1

array([ 2.,  4.,  6.,  8., 10.])

In [44]:
#2d array
arr2 = np.linspace(2,10,6).reshape(2,3)
arr2

array([[ 2. ,  3.6,  5.2],
       [ 6.8,  8.4, 10. ]])

In [46]:
#3d array
arr3 = np.linspace(1,8,8).reshape(2,2,2)
arr3

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

#### Numpy arrays attributes:-
1. dtype
2. ndim
3. shape
4. size
5. itemsize


In [53]:
# 1, dtype:-
arr = np.array([1.1,2.2,3.3,4.4], dtype = int)
arr

array([1, 2, 3, 4])

In [54]:
arr.dtype

dtype('int64')

In [55]:
# 2. ndim:-
arr.ndim

1

In [56]:
# 3. shape:-
arr.shape

(4,)

In [60]:
arr2 = np.arange(1,11).reshape(5,2)
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [61]:
arr2.shape

(5, 2)

In [63]:
# size:-
arr1

array([ 2.,  4.,  6.,  8., 10.])

In [64]:
arr1.size

5

In [65]:
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [66]:
arr2.size

10

In [70]:
# itemsize:-
arr1 = np.array(['a','b'])
arr1.dtype

dtype('<U1')

In [71]:
arr1.itemsize

4

In [89]:
arr2 = np.array([1.1,2.2,3.3])
arr2

array([1.1, 2.2, 3.3])

In [90]:
arr2.dtype

dtype('float64')

In [91]:
arr2.itemsize

8

#### changing dataype of array:-

In [92]:
arr2

array([1.1, 2.2, 3.3])

In [93]:
arr2.astype(int) #temporary operation

array([1, 2, 3])

In [94]:
arr2

array([1.1, 2.2, 3.3])

In [95]:
arr2= arr2.astype(int) 
arr2


array([1, 2, 3])

In [96]:
arr2.dtype

dtype('int64')

In [97]:
arr2.itemsize

8

In [98]:
arr2 = arr2.astype('int32')
arr2.dtype

dtype('int32')

In [99]:
arr2.itemsize

4

In [100]:
arr3 = np.array(['a', 'b'])  # unicode string datatype
arr3

array(['a', 'b'], dtype='<U1')

In [105]:
arr3.astype('S') # changing unicode string to byte string  datatype as it occupies less memory

array([b'a', b'b'], dtype='|S1')

In [106]:
arr = np.array(['a',1.1,6])
arr.dtype

dtype('<U32')

In [109]:
arr = arr.astype(object) 
arr.dtype

dtype('O')

In [112]:
type(arr[0]) #  all elements are string  as NumPy upcasted then as str 

str

In [113]:
type(arr[1])

str

In [114]:
# if we want to store different dtype elements who preserve their python datatype then:

arr1  = np.array(['a',1,2.3], dtype = object)
arr1.dtype

dtype('O')

In [115]:
type(arr1[2])

float

In [116]:
type(arr1[1])

int

#### Array operations:-


In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr*2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr1 = np.arange(1,11).reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
arr1/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ]])

In [9]:
arr1**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000]])

In [12]:
arr1>5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [10]:
arr2 = np.arange(11,21).reshape(2,5)
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
arr1+arr2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [2]:
arr2 = np.arange(11,21).reshape(2,5)
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
arr2*2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [4]:
arr2/2

array([[ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ]])

In [5]:
arr2**3

array([[1331, 1728, 2197, 2744, 3375],
       [4096, 4913, 5832, 6859, 8000]])

In [6]:
arr2>34

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
arr2[arr2<13]

array([11, 12])

In [10]:
arr1 = np.array([1,2,3,4])
arr2 =  np.array([11,22,33,44])

In [11]:
arr1+arr2

array([12, 24, 36, 48])

In [12]:
arr1 * arr2

array([ 11,  44,  99, 176])

In [13]:
arr2

array([11, 22, 33, 44])

In [14]:
arr2.max()

np.int64(44)

In [16]:
np.max(arr2).item()

44

In [17]:
int(arr2.max())

44

In [19]:
arr2.min().item()

11

In [20]:
arr2.mean()
np.mean(arr2)

np.float64(27.5)

In [25]:
# std()
# var()
mx =np.median(arr2).item()

In [26]:
mx

27.5

In [27]:
arr2.sum()

np.int64(110)

In [28]:
arr2

array([11, 22, 33, 44])

In [29]:
arr2.prod()

np.int64(351384)

In [31]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2.sum()

np.int64(45)

In [33]:
arr2.sum(axis = 0)

array([12, 15, 18])

In [34]:
arr2.sum(axis = 1)

array([ 6, 15, 24])

In [35]:
arr2.min(axis = 1)

array([1, 4, 7])

In [ ]:
sin()
cos()
tan()
dot

In [36]:
arr3 = np.arange(11,20).reshape(3,3)
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.dot(arr2,arr3)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [39]:
np.transpose(arr2)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
np.log(arr3)

array([[2.39789527, 2.48490665, 2.56494936],
       [2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898]])

In [43]:
np.exp(arr2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])