In [2]:
import numpy as np

In [3]:
# array()

arr = np.array([1,2,4,5])

In [4]:
arr

array([1, 2, 4, 5])

In [5]:
arr2 = np.array([[1,23,4,5]])

In [6]:
arr2

array([[ 1, 23,  4,  5]])

In [16]:
arr3 = np.array([[1,2,34],[2,4,6]])

In [13]:
arr2.shape

(1, 4)

In [14]:
arr3.shape

(2, 3)

In [17]:
## arange

arr = np.arange(2,10)

In [18]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [24]:
## reshape()
arr = np.arange(1,10).reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr3 = np.arange(1,9).reshape(2,1,2,4)
arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [31]:
arr4 = np.arange(1,121).reshape(5,3,2,4)
arr4

array([[[[  1,   2,   3,   4],
         [  5,   6,   7,   8]],

        [[  9,  10,  11,  12],
         [ 13,  14,  15,  16]],

        [[ 17,  18,  19,  20],
         [ 21,  22,  23,  24]]],


       [[[ 25,  26,  27,  28],
         [ 29,  30,  31,  32]],

        [[ 33,  34,  35,  36],
         [ 37,  38,  39,  40]],

        [[ 41,  42,  43,  44],
         [ 45,  46,  47,  48]]],


       [[[ 49,  50,  51,  52],
         [ 53,  54,  55,  56]],

        [[ 57,  58,  59,  60],
         [ 61,  62,  63,  64]],

        [[ 65,  66,  67,  68],
         [ 69,  70,  71,  72]]],


       [[[ 73,  74,  75,  76],
         [ 77,  78,  79,  80]],

        [[ 81,  82,  83,  84],
         [ 85,  86,  87,  88]],

        [[ 89,  90,  91,  92],
         [ 93,  94,  95,  96]]],


       [[[ 97,  98,  99, 100],
         [101, 102, 103, 104]],

        [[105, 106, 107, 108],
         [109, 110, 111, 112]],

        [[113, 114, 115, 116],
         [117, 118, 119, 120]]]])

In [33]:
# np.linspace()
arr = np.linspace(0,1,4).reshape(2,2)
arr

array([[0.        , 0.33333333],
       [0.66666667, 1.        ]])

In [34]:
# ones()
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# zeros()
arr = np.zeros((2,6)).reshape(3,4)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr = np.zeros((1,))
arr

array([0.])

In [39]:
# identity()
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr = np.random.random((3,4))
arr

array([[0.3175682 , 0.95926698, 0.27383978, 0.7932811 ],
       [0.08997448, 0.6033579 , 0.90111112, 0.8951946 ],
       [0.07596218, 0.41408701, 0.31388494, 0.33217874]])

In [44]:
arr = np.array([1,'4',5.5])
arr

array(['1', '4', '5.5'], dtype='<U32')

In [46]:
l = [1,'4',5.5]
l

[1, '4', 5.5]

In [ ]:
## attributes:-
# shape
# size
# ndim
# dtype
# itemsize

In [48]:
arr.shape

(3,)

In [49]:
arr2.shape

(1, 4)

In [51]:
arr

array(['1', '4', '5.5'], dtype='<U32')

In [50]:
arr.size

3

In [52]:
arr2

array([[ 1, 23,  4,  5]])

In [54]:
arr2.size

4

In [55]:
arr2.ndim

2

In [56]:
arr.ndim

1

In [57]:
arr.dtype

dtype('<U32')

In [58]:
arr2.dtype

dtype('int64')

In [60]:
arr = np.array([1,2,3], dtype = 'float')
arr

array([1., 2., 3.])

In [62]:
# astype()
arr2.astype("float")

array([[ 1., 23.,  4.,  5.]])

In [75]:
arr2 =  arr2.astype("int32")

In [73]:
import sys


In [74]:
sys.getsizeof(arr2)

144

In [76]:
arr2.itemsize

4

In [77]:
arr.itemsize

8